version: "3.9"

services:
  locafy-frontend:
    container_name: locafy-front-end
    build: .
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    networks:
      - default

networks:
  default:
    external:
      name: locafy-net
